"""Remove selected field from Exercice

Revision ID: 3612d0a1dc89
Revises: c73c656d57a0
Create Date: 2025-03-18 17:33:27.111835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3612d0a1dc89'
down_revision = 'c73c656d57a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_exercices')
    with op.batch_alter_table('exercice_tags', schema=None) as batch_op:
        batch_op.alter_column('exercice_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_exercice_tags_exercice_id')
        batch_op.drop_index('ix_exercice_tags_tag_id')
        batch_op.create_foreign_key('fk_tag_exercice', 'tags', ['tag_id'], ['id'])
        batch_op.create_foreign_key('fk_exercice_tag', 'exercices', ['exercice_id'], ['id'])

    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('latex_code',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('correction',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('latex_correction',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('selected')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('latex_correction',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('correction',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('latex_code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('exercice_tags', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exercice_tag', type_='foreignkey')
        batch_op.drop_constraint('fk_tag_exercice', type_='foreignkey')
        batch_op.create_index('ix_exercice_tags_tag_id', ['tag_id'], unique=False)
        batch_op.create_index('ix_exercice_tags_exercice_id', ['exercice_id'], unique=False)
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('exercice_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_exercices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('selected', sa.BOOLEAN(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('latex_code', sa.TEXT(), nullable=False),
    sa.Column('correction', sa.TEXT(), nullable=False),
    sa.Column('latex_correction', sa.TEXT(), nullable=False),
    sa.Column('level_id', sa.INTEGER(), nullable=False),
    sa.Column('theme_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name='fk_exercice_level'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name='fk_exercice_theme'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
